### ISSUE TITLE
local (headset weared user) eyedata and remote (other users) eyedata seems not same data

### ISSUE THREAD

**Issue by kazu0617** [dfgHiatus/NeosVarjoEyeTracking#3]
I tried to check EyeData with other users, but someting not same.

Local: 
Openness: tight changes (current: 0f -> 1f -> 0f | after #2: 0f -> 0.5f -> 1f -> 0.5f -> 0f -> 1f ), and smmothstep not works correctly.
Direction: works.
RawPosition: works. 

Remote: 
Openness: smmothly works without smmothstep.
Direction/RawPosition: not works.

**Comment by dfgHiatus** [comment]
OK, so I understand you other users effectively don't see eye-tracking? May I see your logs?

**Comment by dfgHiatus** [comment]
Closed due to inactivity
